-- 20260421_projects_favorites_tours.sql
-- Adds business metadata fields, project favorites, and tour bookings.
-- Rollback guide:
-- 1) DROP TABLE tour_bookings;
-- 2) DROP TABLE project_favorites;
-- 3) ALTER TABLE projects DROP COLUMN IF EXISTS handover_date, DROP COLUMN IF EXISTS expected_roi_note,
--    DROP COLUMN IF EXISTS map_url, DROP COLUMN IF EXISTS map_embed_url,
--    DROP COLUMN IF EXISTS latitude, DROP COLUMN IF EXISTS longitude;
-- 4) ALTER TABLE houses DROP COLUMN IF EXISTS area;

ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS handover_date DATE,
  ADD COLUMN IF NOT EXISTS expected_roi_note TEXT,
  ADD COLUMN IF NOT EXISTS map_url TEXT,
  ADD COLUMN IF NOT EXISTS map_embed_url TEXT,
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE public.houses
  ADD COLUMN IF NOT EXISTS area NUMERIC(10, 2);

CREATE TABLE IF NOT EXISTS public.project_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, project_id)
);

CREATE TABLE IF NOT EXISTS public.tour_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  house_id BIGINT REFERENCES public.houses (id) ON DELETE SET NULL,
  preferred_date DATE NOT NULL,
  preferred_time TEXT NOT NULL,
  contact_phone TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS project_favorites_user_id_idx
  ON public.project_favorites (user_id);

CREATE INDEX IF NOT EXISTS project_favorites_project_id_idx
  ON public.project_favorites (project_id);

CREATE INDEX IF NOT EXISTS tour_bookings_user_id_idx
  ON public.tour_bookings (user_id);

CREATE INDEX IF NOT EXISTS tour_bookings_project_id_idx
  ON public.tour_bookings (project_id);

CREATE INDEX IF NOT EXISTS tour_bookings_status_idx
  ON public.tour_bookings (status);

CREATE INDEX IF NOT EXISTS tour_bookings_preferred_date_idx
  ON public.tour_bookings (preferred_date);

CREATE OR REPLACE FUNCTION public.set_tour_booking_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_set_tour_booking_updated_at ON public.tour_bookings;

CREATE TRIGGER tr_set_tour_booking_updated_at
BEFORE UPDATE ON public.tour_bookings
FOR EACH ROW
EXECUTE FUNCTION public.set_tour_booking_updated_at();

ALTER TABLE public.project_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tour_bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS project_favorites_select_own ON public.project_favorites;
CREATE POLICY project_favorites_select_own
ON public.project_favorites
FOR SELECT
USING (
  auth.uid() = user_id
  OR COALESCE(
    auth.jwt() -> 'user_metadata' ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    'customer'
  ) IN ('admin', 'employee')
);

DROP POLICY IF EXISTS project_favorites_insert_own ON public.project_favorites;
CREATE POLICY project_favorites_insert_own
ON public.project_favorites
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS project_favorites_delete_own ON public.project_favorites;
CREATE POLICY project_favorites_delete_own
ON public.project_favorites
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS tour_bookings_select_customer_or_staff ON public.tour_bookings;
CREATE POLICY tour_bookings_select_customer_or_staff
ON public.tour_bookings
FOR SELECT
USING (
  auth.uid() = user_id
  OR COALESCE(
    auth.jwt() -> 'user_metadata' ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    'customer'
  ) IN ('admin', 'employee')
);

DROP POLICY IF EXISTS tour_bookings_insert_own ON public.tour_bookings;
CREATE POLICY tour_bookings_insert_own
ON public.tour_bookings
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS tour_bookings_update_customer_or_staff ON public.tour_bookings;
CREATE POLICY tour_bookings_update_customer_or_staff
ON public.tour_bookings
FOR UPDATE
USING (
  auth.uid() = user_id
  OR COALESCE(
    auth.jwt() -> 'user_metadata' ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    'customer'
  ) IN ('admin', 'employee')
)
WITH CHECK (
  auth.uid() = user_id
  OR COALESCE(
    auth.jwt() -> 'user_metadata' ->> 'role',
    auth.jwt() -> 'app_metadata' ->> 'role',
    'customer'
  ) IN ('admin', 'employee')
);
